--
-- ER/Studio Data Architect SQL Code Generation
-- Project :      Final_Project.DM1
--
-- Date Created : Sunday, December 01, 2024 20:23:22
-- Target DBMS : Snowflake
--

-- 
-- TABLE: DIM_CONTRIBUTOR 
--

CREATE TABLE DIM_CONTRIBUTOR(
    CONTRIBUTION_SK        CHAR(10)       NOT NULL,
    CONTRIBUTING_FACTOR    VARCHAR(20),
    DI_CREATED_BY          VARCHAR(20),
    DI_CREATED_DATE        DATE,
    CONSTRAINT PK8 PRIMARY KEY (CONTRIBUTION_SK)
)
;



-- 
-- TABLE: DIM_DATE 
--

CREATE TABLE DIM_DATE(
    DATE_SK            NUMBER(10, 0)    NOT NULL,
    FULL_DT            DATE,
    DAY_NUM            NUMBER(10, 0),
    DAY                VARCHAR(20),
    WEEK_NUM           NUMBER(10, 0),
    MONTH_NUM          NUMBER(10, 0),
    MONTH              VARCHAR(10),
    QUARTER_OF_YEAR    VARCHAR(10),
    YEAR               NUMBER(10, 0),
    SEASON             VARCHAR(20),
    DI_CREATED_BY      VARCHAR(30),
    DI_CREATED_DATE    DATE,
    CONSTRAINT PK1 PRIMARY KEY (DATE_SK)
)
;



-- 
-- TABLE: DIM_LOCATION 
--

CREATE TABLE DIM_LOCATION(
    LOCATION_SK        NUMBER(10, 0)    NOT NULL,
    STREET_NAME        VARCHAR(20),
    CITY               VARCHAR(20),
    LATITUDE           VARCHAR(20),
    LONGITUDE          VARCHAR(20),
    DI_CREATED_BY      VARCHAR(10),
    DI_CREATED_DATE    DATE,
    CONSTRAINT PK3 PRIMARY KEY (LOCATION_SK)
)
;



-- 
-- TABLE: DIM_SOURCE 
--

CREATE TABLE DIM_SOURCE(
    SOURCE_SK          NUMBER(10, 0)    NOT NULL,
    SOURCE             VARCHAR(20),
    DI_CREATED_BY      VARCHAR(20),
    DI_CREATED_DATE    DATE,
    CONSTRAINT PK6 PRIMARY KEY (SOURCE_SK)
)
;



-- 
-- TABLE: DIM_TIME 
--

CREATE TABLE DIM_TIME(
    TIME_SK            NUMBER(10, 0)    NOT NULL,
    TIME               VARCHAR(15),
    TIME_OF_DAY        VARCHAR(10),
    DI_CREATED_BY      NUMBER(10, 0),
    DI_CREATED_DATE    DATE,
    CONSTRAINT PK2 PRIMARY KEY (TIME_SK)
)
;



-- 
-- TABLE: DIM_VEHICLE_INVOLVED 
--

CREATE TABLE DIM_VEHICLE_INVOLVED(
    VEHICLE_SK               CHAR(10)       NOT NULL,
    VEHICLE_INVOLVED_TYPE    VARCHAR(20),
    DI_CREATED_BY            VARCHAR(10),
    DI_CREATED_DATE          DATE,
    CONSTRAINT PK7 PRIMARY KEY (VEHICLE_SK)
)
;



-- 
-- TABLE: FCT_ACC_CONTR 
--

CREATE TABLE FCT_ACC_CONTR(
    ACC_CONTR_SK       NUMBER(10, 0)    NOT NULL,
    CONTRIBUTION_SK    CHAR(10)         NOT NULL,
    ACCIDENT_SK        NUMBER(10, 0)    NOT NULL,
    DI_CREATED_BY      VARCHAR(50),
    DI_CREATED_DATE    DATE,
    CONSTRAINT PK9 PRIMARY KEY (ACC_CONTR_SK, CONTRIBUTION_SK, ACCIDENT_SK)
)
;



-- 
-- TABLE: FCT_ACC_VEH 
--

CREATE TABLE FCT_ACC_VEH(
    ACC_VEH_SK         NUMBER(10, 0)    NOT NULL,
    VEHICLE_SK         CHAR(10)         NOT NULL,
    ACCIDENT_SK        NUMBER(10, 0)    NOT NULL,
    DI_CREATED_BY      VARCHAR(10),
    DI_CREATED_DATE    DATE,
    CONSTRAINT PK5 PRIMARY KEY (ACC_VEH_SK, VEHICLE_SK, ACCIDENT_SK)
)
;



-- 
-- TABLE: FCT_ACCIDENTS 
--

CREATE TABLE FCT_ACCIDENTS(
    ACCIDENT_SK           NUMBER(10, 0)    NOT NULL,
    SOURCE_SK             NUMBER(10, 0)    NOT NULL,
    DATE_SK               NUMBER(10, 0)    NOT NULL,
    TIME_SK               NUMBER(10, 0)    NOT NULL,
    LOCATION_SK           NUMBER(10, 0)    NOT NULL,
    CRASH_ID              VARCHAR(20),
    IS_PEDESTRIAN         CHAR(10),
    IS_MOTORIST           CHAR(10),
    PEDESTRIAN_INJURED    NUMBER(10, 0),
    PEDESTRIAN_KILLED     NUMBER(10, 0),
    MOTORIST_INJURED      NUMBER(10, 0),
    MOTORIST_KILLED       NUMBER(10, 0),
    TOTAL_INJURED         NUMBER(10, 0),
    TOTAL_KILLED          NUMBER(10, 0),
    DI_CREATED_BY         VARCHAR(20),
    DI_CREATED_DATE       DATE,
    CONSTRAINT PK4 PRIMARY KEY (ACCIDENT_SK, SOURCE_SK)
)
;



-- 
-- TABLE: FCT_ACC_CONTR 
--

ALTER TABLE FCT_ACC_CONTR ADD CONSTRAINT RefDIM_CONTRIBUTOR8 
    FOREIGN KEY (CONTRIBUTION_SK)
    REFERENCES DIM_CONTRIBUTOR(CONTRIBUTION_SK)
;

-- 
-- TABLE: FCT_ACC_VEH 
--

ALTER TABLE FCT_ACC_VEH ADD CONSTRAINT RefDIM_VEHICLE_INVOLVED5 
    FOREIGN KEY (VEHICLE_SK)
    REFERENCES DIM_VEHICLE_INVOLVED(VEHICLE_SK)
;

-- 
-- TABLE: FCT_ACCIDENTS 
--

ALTER TABLE FCT_ACCIDENTS ADD CONSTRAINT RefDIM_DATE1 
    FOREIGN KEY (DATE_SK)
    REFERENCES DIM_DATE(DATE_SK)
;

ALTER TABLE FCT_ACCIDENTS ADD CONSTRAINT RefDIM_TIME2 
    FOREIGN KEY (TIME_SK)
    REFERENCES DIM_TIME(TIME_SK)
;

ALTER TABLE FCT_ACCIDENTS ADD CONSTRAINT RefDIM_LOCATION3 
    FOREIGN KEY (LOCATION_SK)
    REFERENCES DIM_LOCATION(LOCATION_SK)
;

ALTER TABLE FCT_ACCIDENTS ADD CONSTRAINT RefDIM_SOURCE4 
    FOREIGN KEY (SOURCE_SK)
    REFERENCES DIM_SOURCE(SOURCE_SK)
;


